# Generated by Django 5.2.6 on 2025-09-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
