# Generated by Django 5.2.6 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_user_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
